export const IndianCities = [
  // Karnataka Major Cities
  "Bengaluru, Karnataka",
  "Mysuru, Karnataka",
  "Hubballi, Karnataka",
  "Dharwad, Karnataka",
  "Mangaluru, Karnataka",
  "Belagavi, Karnataka",
  "Kalaburagi, Karnataka",
  "Davanagere, Karnataka",
  "Ballari, Karnataka",
  "Shivamogga, Karnataka",
  "Tumakuru, Karnataka",
  "Vijayapura, Karnataka",
  "Raichur, Karnataka",
  "Bidar, Karnataka",
  "Hosapete, Karnataka",
  "Gadag, Karnataka",
  "Hassan, Karnataka",
  "Udupi, Karnataka",
  "Bagalkote, Karnataka",
  "Chikkamagaluru, Karnataka",
  "Chitradurga, Karnataka",
  "Kolar, Karnataka",
  "Mandya, Karnataka",
  "Chamarajanagar, Karnataka",
  "Madikeri, Karnataka",
  "Karwar, Karnataka",
  "Yadgir, Karnataka",
  "Koppal, Karnataka",
  "Haveri, Karnataka",
  
  // Major Indian Metros
  "Mumbai, Maharashtra",
  "Delhi, Delhi",
  "Chennai, Tamil Nadu",
  "Kolkata, West Bengal",
  "Hyderabad, Telangana",
  "Ahmedabad, Gujarat",
  "Pune, Maharashtra",
  "Jaipur, Rajasthan",
  "Lucknow, Uttar Pradesh",
  "Kanpur, Uttar Pradesh",
  "Nagpur, Maharashtra",
  "Indore, Madhya Pradesh",
  "Thane, Maharashtra",
  "Bhopal, Madhya Pradesh",
  "Visakhapatnam, Andhra Pradesh",
  "Pimpri-Chinchwad, Maharashtra",
  "Patna, Bihar",
  "Vadodara, Gujarat",
  "Ghaziabad, Uttar Pradesh",
  "Ludhiana, Punjab",
  "Agra, Uttar Pradesh",
  "Nashik, Maharashtra",
  "Faridabad, Haryana",
  "Meerut, Uttar Pradesh",
  "Rajkot, Gujarat",
  "Kalyan-Dombivli, Maharashtra",
  "Vasai-Virar, Maharashtra",
  "Varanasi, Uttar Pradesh",
  "Srinagar, Jammu and Kashmir",
  "Aurangabad, Maharashtra",
  "Dhanbad, Jharkhand",
  "Amritsar, Punjab",
  "Navi Mumbai, Maharashtra",
  "Allahabad, Uttar Pradesh",
  "Ranchi, Jharkhand",
  "Howrah, West Bengal",
  "Coimbatore, Tamil Nadu",
  "Jabalpur, Madhya Pradesh",
  "Gwalior, Madhya Pradesh",
  "Vijayawada, Andhra Pradesh",
  "Jodhpur, Rajasthan",
  "Madurai, Tamil Nadu",
  "Raipur, Chhattisgarh",
  "Kota, Rajasthan",
  "Guwahati, Assam",
  "Chandigarh, Chandigarh",
  "Solapur, Maharashtra"
];
