export const IndianCities = [
  // Karnataka Major Cities (Expanded)
  "Bengaluru, Karnataka",
  "Mysuru, Karnataka",
  "Hubballi-Dharwad, Karnataka",
  "Mangaluru, Karnataka",
  "Belagavi, Karnataka",
  "Kalaburagi, Karnataka",
  "Davanagere, Karnataka",
  "Ballari, Karnataka",
  "Shivamogga, Karnataka",
  "Tumakuru, Karnataka",
  "Vijayapura, Karnataka",
  "Raichur, Karnataka",
  "Bidar, Karnataka",
  "Hosapete, Karnataka",
  "Gadag-Betageri, Karnataka",
  "Hassan, Karnataka",
  "Udupi, Karnataka",
  "Bagalkote, Karnataka",
  "Chikkamagaluru, Karnataka",
  "Chitradurga, Karnataka",
  "Kolar, Karnataka",
  "Mandya, Karnataka",
  "Chamarajanagar, Karnataka",
  "Madikeri (Coorg), Karnataka",
  "Karwar, Karnataka",
  "Yadgir, Karnataka",
  "Koppal, Karnataka",
  "Haveri, Karnataka",
  "Chikkaballapur, Karnataka",
  "Ramanagara, Karnataka",
  "Gokarna, Karnataka",
  "Hampi, Karnataka",
  
  // Major Indian Metros
  "Mumbai, Maharashtra",
  "Delhi, Delhi",
  "Chennai, Tamil Nadu",
  "Kolkata, West Bengal",
  "Hyderabad, Telangana",
  "Ahmedabad, Gujarat",
  "Pune, Maharashtra",
  "Jaipur, Rajasthan",
  "Lucknow, Uttar Pradesh",
  "Kanpur, Uttar Pradesh",
  "Nagpur, Maharashtra",
  "Indore, Madhya Pradesh",
  "Thane, Maharashtra",
  "Bhopal, Madhya Pradesh",
  "Visakhapatnam, Andhra Pradesh",
  "Patna, Bihar",
  "Vadodara, Gujarat",
  "Ghaziabad, Uttar Pradesh",
  "Ludhiana, Punjab",
  "Agra, Uttar Pradesh",
  "Nashik, Maharashtra",
  "Faridabad, Haryana",
  "Meerut, Uttar Pradesh",
  "Rajkot, Gujarat",
  "Varanasi, Uttar Pradesh",
  "Srinagar, Jammu and Kashmir",
  "Amritsar, Punjab",
  "Navi Mumbai, Maharashtra",
  "Ranchi, Jharkhand",
  "Coimbatore, Tamil Nadu",
  "Vijayawada, Andhra Pradesh",
  "Jodhpur, Rajasthan",
  "Madurai, Tamil Nadu",
  "Raipur, Chhattisgarh",
  "Chandigarh, Chandigarh"
];
